default_settings:
  trainer_type: ppo
  hyperparameters:
    batch_size: 1024
    buffer_size: 10240
    learning_rate: 0.0003
    beta: 0.005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
    learning_rate_schedule: linear
  network_settings:
    normalize: false
    hidden_units: 256
    num_layers: 2
    vis_encode_type: simple
  reward_signals:
    extrinsic:
      gamma: 0.99
      strength: 1.0
  keep_checkpoints: 5
  time_horizon: 64

behaviors:
  GridPrey:
    max_steps: 6000000 # 3 times as many prey as hunters
    summary_freq: 30000
  GridHunter:
    max_steps: 2000000
    summary_freq: 10000
    time_horizon: 128 # hunters use longer time horizon and deeper network (fewer to train, more complicated behaviors)
    network_settings:
      num_layers: 3

